### Register
POST http://localhost:7999/api/auth/register
Content-Type: application/json
Connection: keep-alive

{
    "name": "Naina",
    "email": "kamauwainaina29@gmail.com",
    "password": "!123Four"
}
### Login
POST http://localhost:7999/api/auth/login
Content-Type: application/json
Connection: keep-alive

{
    "email": "nainahk470@gmail.com",
    "password": "!123Four"
}

### Register Event
POST http://localhost:7999/api/event/66e87737314277d3a3a11915/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjZkZjAzZWRjNWMxZmVmZDY5ODUzNDBmIiwiZW1haWwiOiJuYWluYWhrNDcwQGdtYWlsLmNvbSIsIm5hbWUiOiJOYWluYSJ9LCJpYXQiOjE3MjY2NTU0NjcsImV4cCI6MTcyNjY1OTA2N30.JW_CKfOSNrQpImKyoRzz8BHAYfFyt1XIYaEqpTqqJWg

### Register Event
POST http://localhost:7999/api/event/66e87737314277d3a3a11915/unregister
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjZkZjAzZWRjNWMxZmVmZDY5ODUzNDBmIiwiZW1haWwiOiJuYWluYWhrNDcwQGdtYWlsLmNvbSIsIm5hbWUiOiJOYWluYSJ9LCJpYXQiOjE3MjY2NTU0NjcsImV4cCI6MTcyNjY1OTA2N30.JW_CKfOSNrQpImKyoRzz8BHAYfFyt1XIYaEqpTqqJWg

### Reset Password
POST http://localhost:7999/api/auth/reset-password
Content-Type: application/json
Connection: keep-alive

{
    "email": "nainahk470@gmail.com"
}
### Test
GET  http://localhost:7999/test

### Create event
POST http://localhost:7999/api/event/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjZkZjAzZWRjNWMxZmVmZDY5ODUzNDBmIiwiZW1haWwiOiJuYWluYWhrNDcwQGdtYWlsLmNvbSIsIm5hbWUiOiJOYWluYSJ9LCJpYXQiOjE3MjU5NjgxOTQsImV4cCI6MTcyNTk3MTc5NH0.jhSVIglyUtG3ffFRsqepGxXbHnieCNmuzbIdKs28HuY
Content-Type: application/json
Connection: keep-alive

{
    "title": "Birthday",
    "description": "My birthday",
    "date": "2021-07-01",
    "time": "12:00",
    "location": "Nairobi",
    "capacity": 10,
    "skipImageUpload": true
}

### Get events
GET http://localhost:7999/api/event/allEvents
Content-Type: application/json